version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juliao
    volumes:
      - .:/app

  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
